services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_WEATHER_API_KEY: ${VITE_WEATHER_API_KEY}
    ports:
      - "3000:3000" # Access the app at http://localhost:3000
    restart: unless-stopped

